### ISSUE TITLE
[Insight] A Symfony2 application should be bootable

### ISSUE THREAD

**Issue by nplhse** [nplhse/Arcella#22]
> SensioLabsInsight was not able to boot your Symfony2 application. If you need to customize files or run commands to make it bootable, you can edit your SensioLabsInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.Heads up! Since this is a new violation, it may explain why other violations have disappeared: SensioLabsInsight needs to boot Symfony applications in order to make dynamic checks.

```
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused in /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
Stack trace:
#0 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(133): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException(&#039;An exception oc...&#039;, Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException))
#2 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, &#039;travis&#039;, NULL, Array)
#3 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#6 /home/foobar/code/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(763): Doctrine\DBAL\Connection->getDatabasePlatform()
#7 /home/foobar/code/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(616): Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform()
#8 /home/foobar/code/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(174): Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping(Object(Doctrine\ORM\Mapping\ClassMetadata))
#9 /home/foobar/code/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#10 /home/foobar/code/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata(&#039;Arcella\\CoreBun...&#039;)
#11 /home/foobar/code/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata(&#039;Arcella\\CoreBun...&#039;)
#12 /home/foobar/code/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(115): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor(&#039;Arcella\\CoreBun...&#039;)
#13 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(69): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata()
#14 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(48): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp(&#039;/home/foobar/co...&#039;)
#15 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(522): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp(&#039;/home/foobar/co...&#039;)
#16 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#17 /home/foobar/code/app/InsightAppKernel.php(15) : eval()&#039;d code(7): Symfony\Component\HttpKernel\Kernel->boot()
#18 /home/foobar/code/app/InsightAppKernel.php(15): eval()
#19 {main}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/7dd6ed21-dfb8-4657-9e17-b8537b6700cd/analyses/96)_

**Comment by nplhse** [comment]
Fixed in commit 8da9fa4.
